#ifndef MACROS_DEFINITION_H
#define MACROS_DEFINITION_H

#define BUFFER_SIZE 100
#define NUMBERS_PER_DRAW 7
#define ALLOCATION_BLOCK_UNIT_SIZE 50
#define NUMBER_OF_AVAILABLE_METRICS 4

#define LOWER_LIMIT_FOR_DRAWN_NUMBER 1
#define UPPER_LIMIT_FOR_DRAWN_NUMBER 49

#define ERROR_INVALID_INPUT_NUMBERS 0
#define ERROR_INVALID_DATA_FILE_NAME 1
#define ERROR_INVALID_DATA_INSIDE_DATA_FILE 2
#define ERROR_MEMORY_ALLOCATION_FAILURE 3

#define METRIC_FREQUENCY_OF_APPEARANCE 0
#define METRIC_DELAY_OF_APPEARANCE 1
#define METRIC_SUM_FREQUENCY_DELAY 2
#define METRIC_RELATIVE_DELAY 3

#endif //MACROS_DEFINITION_H
